import { randomBytes, timingSafeEqual } from "node:crypto";
import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import {
  appManifest,
  exchangeManifestCode,
  githubAppPath,
  saveGitHubApp,
  setInstallationId,
  storedGitHubApp,
} from "@maestro/integrations";
import { arg, has, rejectUnknownFlags, wantsHelp } from "../args.js";
import { checkLine, color } from "../ui.js";

/**
 * The GitHub App manifest flow.
 *
 * Creating an App by hand is a dozen form fields, a permissions matrix nobody wants to
 * reason about, and a private key downloaded to ~/Downloads. GitHub's manifest flow
 * exists to replace that: Maestro states the permissions it needs, GitHub renders one
 * confirmation page, and the credentials come back over a redirect.
 *
 * The permissions in `appManifest` are the security statement worth reading: contents and
 * metadata read, pull requests and issues write — enough to read a diff and post one
 * comment. No write access to code, no administration.
 *
 * The listener binds loopback and lives for one exchange. `state` is a nonce compared in
 * constant length, so a stray request to the callback cannot hand us somebody else's code.
 */
export async function githubApp(argv: string[]): Promise<number> {
  rejectUnknownFlags(argv, ["--force", "--name", "--org", "--webhook-url"]);
  const sub = argv[0];

  if (sub === "show") {
    const app = storedGitHubApp();
    console.log(color.bold("\ngithub app\n"));
    if (!app) {
      console.log(checkLine("info", "not configured", `run 'maestro github-app create'`));
      return 0;
    }
    console.log(checkLine("ok", "app id", app.appId));
    if (app.slug) console.log(checkLine("ok", "slug", app.slug));
    console.log(
      checkLine(
        app.installationId ? "ok" : "warn",
        "installation",
        app.installationId
          ? String(app.installationId)
          : `not set - install the app, then 'maestro github-app installed <id>'`,
      ),
    );
    console.log(checkLine("ok", "private key", `stored 0600 at ${githubAppPath()}`));
    console.log(
      checkLine(
        app.webhookSecret ? "ok" : "info",
        "webhook secret",
        app.webhookSecret ? "generated by GitHub, stored alongside the key" : "none",
      ),
    );
    return 0;
  }

  if (sub === "installed") {
    const id = Number(argv[1]);
    if (!Number.isInteger(id) || id <= 0) {
      console.log(checkLine("fail", "installation id", "expected a positive integer"));
      return 1;
    }
    if (!setInstallationId(id)) {
      console.log(checkLine("fail", "no app stored", "run 'maestro github-app create' first"));
      return 1;
    }
    console.log(checkLine("ok", "installation", String(id)));
    return 0;
  }

  if (sub !== "create") {
    console.log(`
${color.bold("maestro github-app")} <subcommand>

  create [--name <name>] [--org <org>] [--webhook-url <url>]
                              create a GitHub App through GitHub's manifest flow
  installed <installation-id> record which installation to act as
  show                        what is configured
`);
    // Asked for, or got wrong: the same text, two different exit statuses. This command
    // had no `--help` at all, so asking for help was an unknown subcommand.
    return wantsHelp(argv) ? 0 : 1;
  }

  if (storedGitHubApp() && !has(argv, "--force")) {
    console.log(
      checkLine("fail", "already configured", `${githubAppPath()} - pass --force to replace it`),
    );
    return 1;
  }

  const name = arg(argv, "--name") ?? `maestro-${randomBytes(3).toString("hex")}`;
  const org = arg(argv, "--org");
  const webhookUrl = arg(argv, "--webhook-url");
  const state = randomBytes(16).toString("hex");

  let resolve: (v: { code?: string; error?: string }) => void;
  const settled = new Promise<{ code?: string; error?: string }>((r) => {
    resolve = r;
  });

  const server = createServer((req, res) => {
    const url = new URL(req.url ?? "/", "http://127.0.0.1");
    if (url.pathname === "/") {
      // A self-submitting form, because the manifest has to reach GitHub as a POST body
      // and a redirect cannot carry one.
      const manifest = appManifest({
        name,
        redirectUrl: `http://127.0.0.1:${(server.address() as AddressInfo).port}/callback`,
        webhookUrl,
        public: false,
      });
      const action = org
        ? `https://github.com/organizations/${encodeURIComponent(org)}/settings/apps/new?state=${state}`
        : `https://github.com/settings/apps/new?state=${state}`;
      res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
      res.end(
        `<!doctype html><meta charset="utf-8"><title>Creating a GitHub App</title>` +
          `<body style="font:14px system-ui;padding:2rem">` +
          `<p>Sending the app manifest to GitHub…</p>` +
          `<form id="f" method="post" action="${action}">` +
          // `&` first, or the entities introduced below get double-escaped. `<` matters
          // because an app name containing one would otherwise close the attribute's
          // element early and break the form.
          `<input type="hidden" name="manifest" value="${JSON.stringify(manifest)
            .replaceAll("&", "&amp;")
            .replaceAll('"', "&quot;")
            .replaceAll("<", "&lt;")}">` +
          `<noscript><button type="submit">Continue to GitHub</button></noscript>` +
          `</form><script>document.getElementById("f").submit()</script></body>`,
      );
      return;
    }
    if (url.pathname === "/callback") {
      const code = url.searchParams.get("code") ?? undefined;
      // Compared before anything is exchanged: without it, any page the operator happens
      // to have open could drive this callback. Constant-time and length-checked first,
      // because timingSafeEqual throws on a length mismatch — the comment here used to
      // claim constant time over a plain `===`, which is the kind of false claim this
      // project keeps finding in its own commits.
      const given = url.searchParams.get("state") ?? "";
      const ok =
        given.length === state.length && timingSafeEqual(Buffer.from(given), Buffer.from(state));
      res.writeHead(ok && code ? 200 : 400, { "content-type": "text/html; charset=utf-8" });
      res.end(
        `<!doctype html><meta charset="utf-8"><body style="font:14px system-ui;padding:2rem">${
          ok && code
            ? "<p>Done. You can close this tab and go back to the terminal.</p>"
            : "<p>That request did not come from the flow this command started. Nothing was saved.</p>"
        }</body>`,
      );
      resolve(ok && code ? { code } : { error: "state mismatch or missing code" });
      return;
    }
    res.writeHead(404).end();
  });

  await new Promise<void>((r) => server.listen(0, "127.0.0.1", r));
  const port = (server.address() as AddressInfo).port;

  console.log(color.bold("\nmaestro github-app create\n"));
  console.log(checkLine("ok", "app name", name));
  console.log(checkLine("info", "owner", org ? `organization '${org}'` : "your personal account"));
  console.log(
    checkLine(
      webhookUrl ? "ok" : "info",
      "webhook",
      webhookUrl ?? "none - use 'maestro serve --poll', or set one later in the app's settings",
    ),
  );
  console.log(`\n  Open this and confirm:\n\n    ${color.cyan(`http://127.0.0.1:${port}/`)}\n`);
  console.log(color.dim("  Waiting for GitHub to redirect back… (Ctrl-C to give up)\n"));

  const timeout = setTimeout(
    () => resolve({ error: "timed out after 10 minutes" }),
    10 * 60 * 1000,
  );
  const result = await settled;
  clearTimeout(timeout);
  await new Promise<void>((r) => server.close(() => r()));

  if (!result.code) {
    console.log(checkLine("fail", "not created", result.error ?? "no code received"));
    return 1;
  }

  try {
    const app = await exchangeManifestCode(result.code);
    const path = saveGitHubApp(app);
    console.log(checkLine("ok", "created", `app ${app.slug ?? app.appId}`));
    console.log(checkLine("ok", "credentials", `${path} (0600)`));
    if (app.webhookSecret) {
      console.log(checkLine("ok", "webhook secret", "generated by GitHub and stored with the key"));
    }
    console.log(color.bold("\nNext\n"));
    console.log(`  1. Install it on the repositories you want reviewed:`);
    console.log(
      `     ${color.cyan(`${app.htmlUrl ?? "https://github.com/settings/apps"}/installations/new`)}`,
    );
    console.log(`  2. Record which installation to act as:`);
    console.log(`     ${color.cyan("maestro github-app installed <installation-id>")}`);
    console.log(`  3. ${color.cyan("maestro doctor")} to confirm the credential works\n`);
    return 0;
  } catch (err) {
    console.log(
      checkLine("fail", "exchange failed", err instanceof Error ? err.message : String(err)),
    );
    return 1;
  }
}
