import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { type Fixture, splitOf } from "./eval.js";

/**
 * The answer keys in `docs/golden-set/` against the script that builds their repositories.
 *
 * `docs/STATUS.md` findings 232 and 234 report numbers measured on these eight, and neither
 * is checkable by anyone who cannot rebuild them. The keys are hand-written and committed;
 * the repositories are generated by `scripts/seed-golden-set.sh` from the commits that fixed
 * each defect. A key with no row in that script is a key nobody else can use, and nothing
 * else in the repository reads either file — the shape of stale-by-default artefact this
 * project has recorded most often.
 */

const root = join(import.meta.dirname, "../../..");
const dir = join(root, "docs/golden-set");
const seed = readFileSync(join(root, "scripts/seed-golden-set.sh"), "utf8");

const keys = readdirSync(dir)
  .filter((f) => f.endsWith(".json"))
  .map((f) => ({
    file: f,
    fixture: JSON.parse(readFileSync(join(dir, f), "utf8")) as Fixture,
  }));

describe("the committed golden set", () => {
  it("ships keys at all", () => {
    expect(keys.length).toBeGreaterThan(0);
  });

  it("keeps a held-out half and a training half", () => {
    const splits = new Set(keys.map((k) => splitOf(k.fixture)));
    expect(splits).toEqual(new Set(["val", "train"]));
  });

  it.each(keys)("$file is usable and reproducible", ({ file, fixture }) => {
    expect(fixture.name).toBe(file.replace(/\.json$/, ""));
    expect(fixture.expected.length).toBeGreaterThan(0);

    // The committed target is the portable form. `maestro eval` does no tilde expansion,
    // so the seed script rewrites this against MAESTRO_HOME; an absolute path committed
    // here is one machine's and silently scores nothing on every other.
    expect(fixture.target).toBe(`~/.maestro/fixture-repos/${fixture.name}`);

    // Every `/regex/` in the key compiles. `matches` swallows a bad one and returns false,
    // so a typo costs a fixture its recall with no error anywhere.
    for (const e of fixture.expected) {
      if (e.match.startsWith("/") && e.match.lastIndexOf("/") > 0) {
        const end = e.match.lastIndexOf("/");
        expect(
          () => new RegExp(e.match.slice(1, end), e.match.slice(end + 1) || "i"),
        ).not.toThrow();
      }
    }
  });

  it.each(keys)("$file has a provenance row naming a commit in this history", ({ fixture }) => {
    const row = seed.split("\n").find((l) => l.trim().startsWith(`"${fixture.name} `));
    expect(row, `no row for ${fixture.name} in scripts/seed-golden-set.sh`).toBeDefined();

    const sha = row?.trim().split(/\s+/)[1] ?? "";
    expect(sha).toMatch(/^[0-9a-f]{40}$/);
    expect(() =>
      execFileSync("git", ["cat-file", "-e", `${sha}^{commit}`], { cwd: root, stdio: "ignore" }),
    ).not.toThrow();
  });
});
