#!/usr/bin/env node
/**
 * Embeds the built SPA into a TypeScript module.
 *
 * The admin UI has to travel inside the single binary — reading it from disk at runtime
 * would defeat the whole "one self-contained executable" distribution story. Base64 keeps
 * binary assets (fonts, images) intact through the TS source.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const uiDist = join(root, "packages/ui/dist");
const out = join(root, "packages/server/src/ui-assets.generated.ts");

function walk(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) files.push(...walk(full));
    else files.push(full);
  }
  return files;
}

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".woff2": "font/woff2",
  ".json": "application/json",
  ".map": "application/json",
  ".ico": "image/x-icon",
};

if (!existsSync(uiDist)) {
  console.error(`ui build not found at ${uiDist} - run 'pnpm --filter @maestro/ui build' first`);
  process.exit(1);
}

const entries = walk(uiDist).map((full) => {
  const path = `/${relative(uiDist, full).split("\\").join("/")}`;
  const ext = path.slice(path.lastIndexOf("."));
  return {
    path,
    mime: MIME[ext] ?? "application/octet-stream",
    body: readFileSync(full).toString("base64"),
  };
});

const lines = [
  "// GENERATED by scripts/embed-ui.mjs - do not edit.",
  "// The admin SPA is embedded so the binary stays self-contained.",
  "export interface EmbeddedAsset { mime: string; body: string }",
  "export const UI_ASSETS: Record<string, EmbeddedAsset> = {",
  ...entries.map(
    (e) =>
      `  ${JSON.stringify(e.path)}: { mime: ${JSON.stringify(e.mime)}, body: ${JSON.stringify(e.body)} },`,
  ),
  "};",
  `export const UI_BUILT_AT = ${JSON.stringify(new Date().toISOString())};`,
  "",
];

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n"));
const bytes = entries.reduce((n, e) => n + e.body.length, 0);
console.log(
  `embedded ${entries.length} asset(s), ${(bytes / 1024).toFixed(0)}KB base64 -> ${relative(root, out)}`,
);
